spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: hive-crm
      username: ${DB_USER}
      password: ${DB_PASSWORD}